import { describe, expect, it } from "vitest";
import { sanitizePrBody, stripProviderAttribution } from "./pr-body.js";

describe("sanitizePrBody", () => {
	it("trims leading and trailing whitespace", () => {
		expect(sanitizePrBody("  hello world  ")).toBe("hello world");
	});

	it("trims leading and trailing blank lines", () => {
		expect(sanitizePrBody("\n\nhello\n\n")).toBe("hello");
	});

	it("normalizes * bullets to - bullets", () => {
		expect(sanitizePrBody("* item one\n* item two")).toBe("- item one\n- item two");
	});

	it("does not change - bullets", () => {
		expect(sanitizePrBody("- item one\n- item two")).toBe("- item one\n- item two");
	});

	it("normalizes nested * bullets to - bullets", () => {
		expect(sanitizePrBody("* top\n  * nested item")).toBe("- top\n  - nested item");
	});

	it("strips HTML tags", () => {
		expect(sanitizePrBody("hello <b>world</b>")).toBe("hello world");
	});

	it("strips self-closing HTML tags", () => {
		expect(sanitizePrBody("hello<br/>world")).toBe("helloworld");
	});

	it("converts wall of text to bullet points", () => {
		const wall =
			"Added new endpoint for users. Fixed validation bug. Updated tests to cover edge cases.";
		const result = sanitizePrBody(wall);
		expect(result).toContain("- Added new endpoint for users");
		expect(result).toContain("- Fixed validation bug");
		expect(result).toContain("- Updated tests to cover edge cases");
	});

	it("does not split text that already has newlines", () => {
		const formatted = "- Added new endpoint\n- Fixed bug";
		expect(sanitizePrBody(formatted)).toBe("- Added new endpoint\n- Fixed bug");
	});

	it("returns empty string for empty input", () => {
		expect(sanitizePrBody("")).toBe("");
	});

	it("returns empty string for whitespace-only input", () => {
		expect(sanitizePrBody("   \n\n  ")).toBe("");
	});

	it("preserves markdown formatting like bold and code", () => {
		expect(sanitizePrBody("**bold** and `code`")).toBe("**bold** and `code`");
	});
});

describe("stripProviderAttribution", () => {
	it("strips Claude Code attribution with claude.ai link", () => {
		const body =
			"## Summary\n- Added feature\n\n---\n🤖 Generated with [Claude Code](https://claude.ai/code)\n\nCo-Authored-By: Claude <noreply@anthropic.com>";
		expect(stripProviderAttribution(body)).toBe("## Summary\n- Added feature");
	});

	it("strips Gemini CLI attribution", () => {
		const body = "## Summary\n- Fixed bug\n\n---\n*Generated by Gemini CLI*";
		expect(stripProviderAttribution(body)).toBe("## Summary\n- Fixed bug");
	});

	it("strips OpenAI Codex attribution", () => {
		const body =
			"## Summary\n- Refactored code\n\n---\n🤖 Generated with [OpenAI Codex](https://openai.com/codex)";
		expect(stripProviderAttribution(body)).toBe("## Summary\n- Refactored code");
	});

	it("does not strip body without provider attribution", () => {
		const body = "## Summary\n- Feature A\n- Feature B";
		expect(stripProviderAttribution(body)).toBe("## Summary\n- Feature A\n- Feature B");
	});

	it("does not strip --- sections that are not provider attributions", () => {
		const body = "## Before\n\n---\n\n## After\n- Some content";
		expect(stripProviderAttribution(body)).toBe("## Before\n\n---\n\n## After\n- Some content");
	});

	it("preserves useful content before the attribution section", () => {
		const body =
			"## Summary\n- Feature A\n\n## Details\nSome details here\n\n---\n🤖 Generated with [Claude Code](https://claude.ai/code)";
		expect(stripProviderAttribution(body)).toBe(
			"## Summary\n- Feature A\n\n## Details\nSome details here",
		);
	});

	it("strips trailing Co-Authored-By AI lines outside --- blocks", () => {
		const body = "## Summary\n- Feature A\n\nCo-Authored-By: Claude <noreply@anthropic.com>";
		expect(stripProviderAttribution(body)).toBe("## Summary\n- Feature A");
	});

	it("preserves Co-Authored-By lines for human contributors", () => {
		const body = "## Summary\n- Feature A\n\nCo-Authored-By: Alice <alice@example.com>";
		expect(stripProviderAttribution(body)).toBe(
			"## Summary\n- Feature A\n\nCo-Authored-By: Alice <alice@example.com>",
		);
	});

	it("handles body with no --- separator", () => {
		const body = "Simple description";
		expect(stripProviderAttribution(body)).toBe("Simple description");
	});

	it("handles empty body", () => {
		expect(stripProviderAttribution("")).toBe("");
	});

	it("strips Aider attribution", () => {
		const body = "## Summary\n- Added tests\n\n---\nGenerated by Aider";
		expect(stripProviderAttribution(body)).toBe("## Summary\n- Added tests");
	});

	it("strips GitHub Copilot attribution", () => {
		const body = "## Summary\n- Fixed issue\n\n---\nGenerated by GitHub Copilot";
		expect(stripProviderAttribution(body)).toBe("## Summary\n- Fixed issue");
	});
});
